name: Publish to npm

on:
  push:
    branches:
      - main # Trigger the workflow only on pushes to the main branch

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        run: npm install -g pnpm@latest npm@latest

      - name: Clean install dependencies
        run: pnpm install --frozen-lockfile

      - name: Increment patch version
        run: pnpm version patch --no-git-tag-version

      - name: Commit version changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "ci: bump version to $(node -p "require('./package.json').version") [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Use npm instead of pnpm to publish to avoid issues with npm registry authentication
      - name: Publish to npm
        run: npm publish

      # Ensure we push the version change only after a successful publish
      - name: Push version changes
        run: git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}